# CustomAuth Causing Runtime Error On Vercel Serverless Functions Environment
## Screenshot
![](./vercel_runtime_error.png)

## Endpoint
https://custom-auth-vercel-bug.vercel.app/api/hello

## Logs
 https://vercel.com/coral/custom-auth-vercel-bug/GLX6dmXNNB2WGaiR3nZocg6DnH2H/functions

## Related Issues
- https://github.com/nhost/nhost/issues/419