# CustomAuth Causing Runtime Error On Vercel Serverless Functions Environment
Runtime error screenshot:
![](./vercel_runtime_error.png)
Endpoint returning 500 code: https://custom-auth-vercel-bug.vercel.app/api/hello
Logs: https://vercel.com/coral/custom-auth-vercel-bug/GLX6dmXNNB2WGaiR3nZocg6DnH2H/functions
